# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: projects/core
    - method: pip
      path: projects/procedures
      extra_requirements:
        - llm
    - requirements: docs/requirements.txt

# Build all formats (HTML is default; PDF/EPUB optional)
formats:
  - html
  # - pdf
  # - epub
